apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-resolved.yaml --profile k8s convert --out deployment
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: adminer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-resolved.yaml --profile k8s convert --out deployment
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/surrogate-optimisation-example: "true"
        io.kompose.service: adminer
    spec:
      containers:
        - image: adminer:4.7.9-standalone
          name: surrogate-optimisation-example-adminer
          ports:
            - containerPort: 8080
              hostPort: 8081
              protocol: TCP
          resources: {}
      hostname: adminer
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
status: {}
