apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-resolved.yaml --profile k8s convert --out deployment
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nodeexporter
  name: nodeexporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodeexporter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-resolved.yaml --profile k8s convert --out deployment
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/surrogate-optimisation-example: "true"
        io.kompose.service: nodeexporter
    spec:
      containers:
        - args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($()|/)
          image: prom/node-exporter:v1.5.0
          name: surrogate-optimisation-example-nodeexporter
          ports:
            - containerPort: 9100
              hostPort: 9100
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /host/proc
              name: nodeexporter-claim0
              readOnly: true
            - mountPath: /host/sys
              name: nodeexporter-claim1
              readOnly: true
            - mountPath: /rootfs
              name: nodeexporter-claim2
              readOnly: true
      hostname: nodeexporter
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
        - name: nodeexporter-claim0
          persistentVolumeClaim:
            claimName: nodeexporter-claim0
            readOnly: true
        - name: nodeexporter-claim1
          persistentVolumeClaim:
            claimName: nodeexporter-claim1
            readOnly: true
        - name: nodeexporter-claim2
          persistentVolumeClaim:
            claimName: nodeexporter-claim2
            readOnly: true
status: {}
