apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-resolved.yaml --profile k8s convert --out deployment
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: portainer
  name: portainer
spec:
  ports:
    - name: "9443"
      port: 9443
      targetPort: 9000
  selector:
    io.kompose.service: portainer
status:
  loadBalancer: {}
