apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-resolved.yaml --profile k8s convert --out deployment
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: portainer
  name: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: portainer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-resolved.yaml --profile k8s convert --out deployment
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/surrogate-optimisation-example: "true"
        io.kompose.service: portainer
    spec:
      containers:
        - args:
            - -H
            - unix:///var/run/docker.sock
          image: portainer/portainer-ce:linux-arm64-2.18.2
          name: surrogate-optimisation-example-portainer
          ports:
            - containerPort: 9000
              hostPort: 9443
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: portainer-claim0
            - mountPath: /data
              name: portainer-data
      hostname: portainer
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
        - name: portainer-claim0
          persistentVolumeClaim:
            claimName: portainer-claim0
        - name: portainer-data
          persistentVolumeClaim:
            claimName: portainer-data
status: {}
