apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-resolved.yaml --profile k8s convert --out deployment
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: prefect-agent
  name: prefect-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prefect-agent
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-resolved.yaml --profile k8s convert --out deployment
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/surrogate-optimisation-example: "true"
        io.kompose.service: prefect-agent
    spec:
      containers:
        - command:
            - /opt/prefect/entrypoint.sh
            - prefect
            - agent
            - start
            - -q
            - queue
          env:
            - name: PREFECT_API_URL
              value: http://prefect-server:4200/api
          image: prefecthq/prefect:2.13.2-python3.10
          name: surrogate-optimisation-example-prefect-agent
          resources: {}
      hostname: prefect-agent
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
status: {}
